name: Java CI with Maven

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 24
      uses: actions/setup-java@v4
      with:
        java-version: '24'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven (skip tests)
      run: |
        cd biblioteca
        mvn clean install -DskipTests

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: biblioteca-jar
        path: biblioteca/target/*.jar

  test:
    needs: build
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 24
      uses: actions/setup-java@v4
      with:
        java-version: '24'
        distribution: 'temurin'
        cache: maven

    - name: Run Maven tests and generate reports
      run: |
        cd biblioteca
        mvn test surefire-report:report site -Dmaven.test.failure.ignore=true

    - name: Upload test reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-reports
        path: |
          biblioteca/target/surefire-reports/
          biblioteca/target/site/

  notification:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Notification
      env:
        EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}
      run: sh scripts/sendEmail.sh
